### ISSUE TITLE
...ANY.type is not iterable

### ISSUE THREAD

**Issue by aliciahogue** [alt3/sequelize-to-json-schemas#63] opened 2020-02-10 16:31 UTC
Seems like the esm module is throwing an error on the line referenced below.  ...ANY.type is not iterable

If I change the code to ...ANY.anyOf it is fine

https://github.com/alt3/sequelize-to-json-schemas/blob/f182cca39235d70625a69de7f0a49b02044e5a96/lib/type-mapper.js#L345

**Comment by bravo-kernel** [comment] 2020-02-10 16:45
Thanks for reporting. I have a feeling this may have been caused by this change https://github.com/alt3/sequelize-to-json-schemas/commit/1776f9abfa811ae7a6fd4ab10aaa3ca13f0f7383#diff-47fec86a2083ec6f9bb39a04c1b10baeL4.

If you could provide a PR with suggested fix that would be highly appreciated. I am not able to make one short-term and that way we can also see if tests continue to pass.

**Comment by bravo-kernel** [comment] 2020-02-10 16:56
Good catch too, I wonder if I could add a test to prevent this from happening in the future. If you have some code/example to help me understand how to reproduce please do share it ❤️

**Comment by brayden-bcgsc** [comment] 2020-02-10 17:04
That's my bad, I must have missed that any when making the 'ANY' changes. You could probably just remove the type 
`result = { ...ANY }` 
like the 'ANY's' in the earlier sections of the type-mapper.

**Comment by bravo-kernel** [comment] 2020-02-10 17:15
@brayden-bcgsc thanks for confirming, if you have ideas on how to test against this...

**Comment by brayden-bcgsc** [comment] 2020-02-10 17:43
I would probably just add a new test like the ones you have already for a type that isn't in the type-mapper and the default type will have to be used. What type did @aliciahogue use that isn't mapped that resorted to using the default?

Maybe a better solution would be to add all the valid Sequelize data types.
https://sequelize.org/master/variable/index.html#static-variable-DataTypes
Or explicitly add the data types you currently support and throw an error if it is not one of the supported data types.

**Comment by aliciahogue** [comment] 2020-02-11 17:15
It looks like it is the  DataTypes.VIRTUAL() that threw the error.

**Comment by bravo-kernel** [comment] 2020-02-26 20:10
@aliciahogue just merged a PR by @brayden-bcgsc that should resolve this. Could you verify and close this ticket? 

Apologies for the late response on this one ❤️

**Comment by bravo-kernel** [comment] 2020-03-14 09:35
Closing due to lack of response.

**Closed by bravo-kernel** 2020-03-14 09:35 UTC
